scripts: Print call stack when error
Tested with:
./build.sh
^CERROR: Running ./build.sh - run_build_hooks failed!
ERROR: exit code 130 from line 118:
    tee -a "$LOG_FILE"
ERROR: call stack:
    build.sh: run_build_hooks(120)
    build.sh: main(323)
    build.sh: main(334)

Change-Id: I1cd336368d57d3fa157966bda7e0797e014e7413
Signed-off-by: Jeffy Chen <jeffy.chen@rock-chips.com>

diff --git a/common/scripts/build-helper b/common/scripts/build-helper
--- a/common/scripts/build-helper
+++ b/common/scripts/build-helper
@@ -10,12 +10,18 @@ fi
 
 err_handler()
 {
-	ret=$?
+	ret=${1:-$?}
 	[ "$ret" -eq 0 ] && return
 
-	echo "ERROR: Running $0 - ${FUNCNAME[1]} failed!"
+	echo "ERROR: Running $0 - ${2:-${FUNCNAME[1]}} failed!"
 	echo "ERROR: exit code $ret from line ${BASH_LINENO[0]}:"
-	echo "    $BASH_COMMAND"
+	echo "    ${3:-$BASH_COMMAND}"
+	echo "ERROR: call stack:"
+	for i in $(seq 1 $((${#FUNCNAME[@]} - 1))); do
+		SOURCE="${BASH_SOURCE[$i]}"
+		LINE=${BASH_LINENO[$(( $i - 1 ))]}
+		echo "    $(basename "$SOURCE"): ${FUNCNAME[$i]}($LINE)"
+	done
 	exit $ret
 }
 trap 'err_handler' ERR
@@ -35,6 +41,12 @@ try_func()
 
 	echo -e "# $(date +"%F %T") -- $@\n" >> "$LOG_FILE"
 	$@ 2>&1 | tee -a "$LOG_FILE"
+
+	FUNC_RET=${PIPESTATUS[0]}
+	if [ $FUNC_RET -ne 0 ]; then
+		err_handler $FUNC_RET "${FUNCNAME[0]} $*" "$@"
+		exit $FUNC_RET
+	fi
 
 	case "$2" in
 		# Unconditional hook
diff --git a/common/scripts/post-helper b/common/scripts/post-helper
--- a/common/scripts/post-helper
+++ b/common/scripts/post-helper
@@ -10,12 +10,18 @@ fi
 
 err_handler()
 {
-	ret=$?
+	ret=${1:-$?}
 	[ "$ret" -eq 0 ] && return
 
-	echo "ERROR: Running $0 - ${FUNCNAME[1]} failed!"
+	echo "ERROR: Running $0 - ${2:-${FUNCNAME[1]}} failed!"
 	echo "ERROR: exit code $ret from line ${BASH_LINENO[0]}:"
-	echo "    $BASH_COMMAND"
+	echo "    ${3:-$BASH_COMMAND}"
+	echo "ERROR: call stack:"
+	for i in $(seq 1 $((${#FUNCNAME[@]} - 1))); do
+		SOURCE="${BASH_SOURCE[$i]}"
+		LINE=${BASH_LINENO[$(( $i - 1 ))]}
+		echo "    $(basename "$SOURCE"): ${FUNCNAME[$i]}($LINE)"
+	done
 	exit $ret
 }
 trap 'err_handler' ERR
